# golangci-lint v2 configuration for jp-go-testcontainers-postgres
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gosec

  settings:
    staticcheck:
      checks: ["all", "-ST1000", "-ST1016", "-ST1005"]

    gosec:
      excludes:
        - G104
        - G301
        - G306

  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"
      - ".*_generated\\.go$"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
